INSERT INTO bears (name, age, gender, color, temperment) VALUES ("Mr. Chocolate", 18, "Male", "brown", "Sleepy" )
INSERT INTO bears (name, age, gender, color, temperment) VALUES ("Rowdy", 16, "Male", "brown", "Sleepy" )
INSERT INTO bears (name, age, gender, color, temperment) VALUES ("Mr. Chocolate", 18, "Male", "brown", "Sleepy" )
INSERT INTO bears (name, age, gender, color, temperment) VALUES ("Mr. Chocolate", 18, "Male", "brown", "Sleepy" )
INSERT INTO bears (name, age, gender, color, temperment) VALUES ("Mr. Chocolate", 18, "Male", "brown", "Sleepy" )
INSERT INTO bears (name, age, gender, color, temperment) VALUES ("Mr. Chocolate", 18, "Male", "brown", "Sleepy" )
INSERT INTO bears (name, age, gender, color, temperment) VALUES ("Mr. Chocolate", 18, "Male", "brown", "Sleepy" )
INSERT INTO bears (name, age, gender, color, temperment) VALUES (nil, 18, "Male", "brown", "Sleepy" )